name: Run Script and Push Changes

on: 
  workflow_dispatch:   
    inputs:
      bff_version:
        description: 'Enter the bff_version'
        required: true  
        default: 'v1.0.0-rc'  
        
permissions:
  contents: write 

jobs:
  create_rc_and_push:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout the codebase
      uses: actions/checkout@v3  

    - name: Set up Git for authentication
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Run createRc.sh script
      run: |
        chmod +x ./scripts/createRc.sh 
        ./createRc.sh -b ${{ github.event.inputs.bff_version }}  

    - name: Verify changes before pushing
      run: |
        git status  

    - name: Commit and push changes
      run: |
        git add . 
        git commit -m "Automated update by GitHub Actions: Creating RC for version ${{ github.event.inputs.bff_version }}"  
        git push origin HEAD  
