name: Workflow dispatch choice input example
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'the environment to deploy to'
        required: true
        defualt: 'production'
        type: choice
        options:
          - dev
          - production
          - qa


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to ${{github.event.inputs.environment}} environment"