name: Workflow dispatch freeform input example
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'the environment to deploy to'
        required: true
        default: 'production'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to ${{github.event.inputs.environment}} environment"